name: Continuous Integration

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup Node 16 environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Ensure Linting
        run: yarn lint
      - name: Audit Dependencies
        run: yarn audit --groups dependencies
      - name: Run Jest tests
        run: yarn test
